INSERT INTO ACCOUNT(NAME, CURRENCY, BALANCE, TREASURY) VALUES ('John', 'USD', 500, FALSE);
INSERT INTO ACCOUNT(NAME, CURRENCY, BALANCE, TREASURY) VALUES ('Sarah', 'USD', 1000, FALSE);
INSERT INTO ACCOUNT(NAME, CURRENCY, BALANCE, TREASURY) VALUES ('Lukas', '€', 300, TRUE);